### PR TITLE
make bot think

### PR DESCRIPTION
**Pull request by andy-k**
🤔 :trollface: 🤔

### CODE REVIEW

**Comment by domino14** [comment]
I think this is too much of a change for this particular bot. We can use it for other bots though.

**Comment by martindemello** [comment]
historical precedent: https://lettersremain.com/intentional-delays-in-apple-chess-so-you-dont-feel-so-bad/

**Comment by domino14** [comment]
Yep I definitely have read this as well. The only reason I’m rejecting this
for now is because those bots already have a known speed.. (instant). One
good approach might be to make HastyBot instant and not the rest?

**Pull request closed without merging**
