### PR TITLE
starting refactor

### PR DESCRIPTION
**Pull request by domino14**
Refactor board to be simpler and match some aspects of the `wolges` data structures a bit more.

Goals for this refactor:
- Greatly lessen the number of allocations; use a couple of 1-d arrays of bytes to represent board state instead of complex `Square` pointer per board square
- Separate cross-sets from the board structure; tie them with the movegen. This will allow us to run experiments with bots that know different words.
- Get to a level where we can separate the crossword game logic and movegen/AI logic into separate repos. This might be possible after this refafctor.

Future:
- Use Kurnia word graph structures for faster movegen
    - this will also involve re-indexing the specific alphabets to start at 1 instead of 0

### CODE REVIEW

**Comment by domino14** [comment]
To fix:
- bot
- automatic analyzer
- shell (specifically issue in #153)

**Comment by domino14** [comment]
This branch might sadly be outdated and should mostly be ignored. A few of its changes have already been merged into master.

**Comment by ddugovic** [comment]
To help determine what can be salvaged, I'm starting a branch `board-refactor-2` and merge `master` into it.  Since `board-refactor` is incomplete this won't be complete either, but at least the diff will be easier to read.

After resolving easier merge conflicts, only 61 conflicts remain:
```
        both modified:   ai/player/utils.go
        both modified:   automatic/game_runner.go
        both modified:   board/board.go
        both modified:   board/board_utils.go
        both modified:   cross_set/cross_set.go
        both modified:   cross_set/cross_set_test.go
        both modified:   endgame/alphabeta/alphabeta.go
        both modified:   endgame/alphabeta/alphabeta_test.go
        both modified:   endgame/alphabeta/gamenode.go
        both modified:   game/backup.go
        both modified:   game/game.go
        both modified:   montecarlo/montecarlo_test.go
        both modified:   movegen/movegen.go
        both modified:   movegen/movegen_test.go
        both modified:   strategy/exhaustive_leave_test.go

➜  macondo git:(board-refactor-2) ✗ grep -wr "====" --include='*.go' | wc -l
61
```

**Comment by domino14** [comment]
this is unlikely to ever be merged in. it's ok.

**Pull request closed without merging**
